### ISSUE TITLE
Physical gripper not responding to publishers

### ISSUE THREAD

**Issue by bleubirb** [ian-chuang/OnRobot_RG2-FT_ROS#4]
Hi, I'm trying to control the gripper via the Publisher-Subscriber interface. I'm currently entering the command like this:
```
rostopic pub /command onrobot_rg2ft_msgs/RG2FTCommand "TargetForce: 0
TargetWidth: 500
Control: 1"
```
and I'm getting a response:
```
publishing and latching message. Press ctrl-C to terminate
```
But no response is occurring from the gripper. I'm able to successfully move the gripper via RVIZ, making me feel confident in my physical connections, along with being able to ping the gripper. Alongside this, when I sanity check via `rostopic echo /command` in another terminal, I can see the input is successful. 

The other thing is in the log, it says that the subscriber count is 0. 
![image](https://github.com/ian-chuang/OnRobot-RG2FT-ROS/assets/62669343/c5fc915c-2c7a-4510-83fe-4874c56e871f)

I'm a bit new to ROS, so any help would be appreciated with this problem!

**Comment by ian-chuang** [comment]
Hello,

Try increasing the force to 30-400. If the force is 0 the gripper won't move. Also try to see if you can rostopic echo the gripper state topic. If you are receiving values from the state then I think the driver should be working so I'm not sure why the command topic wouldn't work.

**Comment by bleubirb** [comment]
Hi,

That worked! Thank you. I can rostopic echo the gripper state as well. Would you happen to know why you have to set the TargetForce to >=30? Just out of curiosity.

**Comment by ian-chuang** [comment]
Sorry it is my mistake for not making clear in code/docs. The gripper force range is 3-40N from what I remember. So too low a value doesn't seem to move the gripper.

**Comment by bleubirb** [comment]
No worries, that makes sense. The minimum value seems to be 2N from running it on the gripper.

 And once again, I appreciate the help!
