### ISSUE TITLE
compatibility

### ISSUE THREAD

**Issue by shizi-19** [ian-chuang/OnRobot_RG2-FT_ROS#5]
Hi, thanks for sharing the package! 
I am wondering if this driver works for the Onrobot RG2 gripper?

**Comment by ian-chuang** [comment]
Hi

There are other drivers that should work with the RG2:
https://github.com/Osaka-University-Harada-Laboratory/onrobot/tree/main

Unfortunately the communication commands are different between RG2-FT and RG2. It shouldn't be too hard to modify the code to match the RG2 though.

Check page 60 and 62 here:
https://onrobot.com/sites/default/files/documents/User_Manual_for_TECHMAN_OMRON_TM_v1.05_EN_0.pdf

**Comment by Leon-0919** [comment]
@ian-chuang I will look into it thanks a lot for the quick reply!
